### ISSUE TITLE
Feature/Bug - allow no params in workflow steps

### ISSUE THREAD

**Issue by dpastoor** [Gilead-BioStats/gsm.core#31]
## Feature Details

Currently, all RunStep invocations need params. This is common for the piplines, however functions that have all defaults or no parameters currently fail.

## Example Code

in using the following example used for custom reporting pipeline that needs a custom function, in this case with a default
```
s0001_hello_world <- function(output_file = "hello_world.html") {
	html_content <- "<!DOCTYPE html>
<html>
<head>
    <title>Hello World</title>
</head>
<body>
    <h1>Hello, World!</h1>
</body>
</html>"

	writeLines(html_content, con = output_file)
	message("HTML page rendered to: ", output_file)
	return(output_file)
}
```

a custom report yaml would look like the following:

```
meta:
  Type: Report
  ID: HelloWorld 
  Output: html
  Name: HelloWorld!
  Description: A report that says hi
  Category: Custom
steps:
- output: output_report
  name: s0001_hello_world
```

however this currently errors

```
── Evaluating 0 parameter(s) for `s0001_hello_world` 

── Calling `s0001_hello_world` 
Error in `do.call()`:
! second argument must be a list
```

do to how do.call is invoked
